export const META_KEYWORDS = [
  "Hem Bahadur Pun",
  "Hem Bahadur Pun Portfolio",
  "Front-end Engineer",
  "React Developer",
  "Next.js Developer",
  "React Developer in Nepal",
  "Next.js Developer in Nepal",
  "Front-end Engineer in Nepal",
  "Front-end Engineer in Kathmandu",
  "React Developer in Kathmandu",
  "Next.js Developer in Kathmandu",
  "Front-end Engineer in Nepal",
  "React Developer in Nepal",
  "Next.js Developer in Nepal",
  "Front-end Engineer in Kathmandu",
  "React Developer in Kathmandu",
  "Full Stack Developer",
  "Full Stack Developer in Nepal",
  "Full Stack Developer in Kathmandu",
  "Full Stack Developer in Nepal",
  "Best Full Stack Developer in Nepal",
  "Best Full Stack Developer in Kathmandu",
  "Best Full Stack Developer",
  "Best Full Stack Developer in Nepal",
];
